DROP TABLE STUDENTS, ATTENDANCE;
CREATE TABLE STUDENTS (STUDENT_ID INT PRIMARY KEY, NAME VARCHAR(50));
CREATE TABLE ATTENDANCE (ATT_ID INT PRIMARY KEY, STUDENT_ID INT, DATE DATE, STATUS VARCHAR(10), FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID));
INSERT INTO STUDENTS VALUES (1,'Zahan'),(2,'Swara'),(3,'Rishi');
INSERT INTO ATTENDANCE VALUES (1,1,'2025-10-01','PRESENT'),
							  (2,1,'2025-10-02','ABSENT'),
                              (3,2,'2025-10-01','PRESENT'),
                              (4,3,'2025-10-01','PRESENT'),
                              (5,3,'2025-10-02','PRESENT');
SELECT * FROM STUDENTS;
SELECT *FROM ATTENDANCE;
SELECT S.NAME,SUM(CASE WHEN A.STATUS='PRESENT' THEN 1 ELSE 0 END) AS DAYS_PRESENT,COUNT(A.ATT_ID) AS TOTAL_DAYS,(SUM(CASE WHEN A.STATUS='PRESENT' THEN 1 ELSE 0 END)*100.0/COUNT(A.ATT_ID)) AS ATTENDANCE_PERCENT FROM STUDENTS S JOIN ATTENDANCE A ON S.STUDENT_ID=A.STUDENT_ID GROUP BY S.NAME;
