DROP TABLE BOOKS;
CREATE TABLE BOOKS (BOOK_ID INT PRIMARY KEY, TITLE VARCHAR(100), AUTHOR VARCHAR(50), AVAILABLE BOOLEAN);
INSERT INTO BOOKS VALUES (1,'1984','GEORGE ORWELL',TRUE),(2,'THE HOBBIT','J.R.R. TOLKIEN',FALSE),(3,'PRIDE AND PREJUDICE','JANE AUSTEN',TRUE),(4,'THE ALCHEMIST','PAULO COELHO',TRUE);
SELECT * FROM BOOKS;
SELECT TITLE FROM BOOKS WHERE AVAILABLE=TRUE;
UPDATE BOOKS SET AVAILABLE=FALSE WHERE BOOK_ID=3;