DROP TABLE MOVIES, REVIEWS;
CREATE TABLE MOVIES (MOVIE_ID INT PRIMARY KEY, TITLE VARCHAR(100), GENRE VARCHAR(30));
CREATE TABLE REVIEWS (REVIEW_ID INT PRIMARY KEY, MOVIE_ID INT, REVIEWER VARCHAR(50), RATING INT, FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID));
INSERT INTO MOVIES VALUES (1,'INCEPTION','SCI-FI'),
						  (2,'TITANIC','ROMANCE'),
                          (3,'AVENGERS','ACTION');
INSERT INTO REVIEWS VALUES (1,1,'Zahan',9),
						   (2,1,'Rishi',8),
                           (3,2,'Swara',7),
                           (4,3,'Katherine',9);
SELECT M.TITLE,AVG(R.RATING) AS AVG_RATING FROM MOVIES M JOIN REVIEWS R ON M.MOVIE_ID=R.MOVIE_ID GROUP BY M.TITLE ORDER BY AVG_RATING DESC;
