DROP TABLE STUDENT;
CREATE TABLE STUDENT (STUDENT_ID INT PRIMARY KEY, NAME VARCHAR(50), GRADE INT, MARKS INT); 
INSERT INTO STUDENT VALUES (1,'Zahan',12,87),
							(2,'Rishi',12,73),
                            (3,'Swara',10,92),
                            (4,'Katherine',9,65),
                            (5,'Vihaan',10,78); 
SELECT * FROM STUDENT;
SELECT NAME,MARKS FROM STUDENT WHERE MARKS>80;
SELECT GRADE,AVG(MARKS) AS AVG_MARKS FROM STUDENT GROUP BY GRADE;